### ISSUE TITLE
update to latest trafilatura v1.4.1

### ISSUE THREAD

**Issue by derekperkins** [markusmobius/go-trafilatura#1]
> The structure of this package is arranged following the structure of original Python code. This way, any improvements from the original can be implemented easily here

How difficult would it be to include improvements from v0.8.2 to the current v1.4.1?

**Comment by derekperkins** [comment]
The diff isn't small, but the majority appears to be test html file changes.
https://github.com/adbar/trafilatura/compare/v1.4.1..v0.8.2

cc @mordfustang21

**Comment by markusmobius** [comment]
We are working write now on bringing repo up to date with the latest version. It should take about a month.

**Comment by derekperkins** [comment]
Awesome, thanks for the great library!

**Comment by RadhiFadlillah** [comment]
Forgot to mention that the library has been updated to v1.5.0 [last month](https://github.com/markusmobius/go-trafilatura/commit/fb150fd41ed27b989af9807b7bbc29b05ebd98d7), so I'll close this issue :smiley:
