### ISSUE TITLE
support html output from the library

### ISSUE THREAD

**Issue by derekperkins** [markusmobius/go-trafilatura#2]
It would be nice if there was a library method for outputting the html nodes from the library, similar to how it is done in the cli, which is difficult to copy since it references internal functions.
https://github.com/markusmobius/go-trafilatura/blob/main/cmd/go-trafilatura/output.go#L81-L147

**Comment by RadhiFadlillah** [comment]
In the latest version there is a helper function named [`CreateReadableDocument`](https://pkg.go.dev/github.com/markusmobius/go-trafilatura@v0.0.0-20230519102354-c250c06a3b8d#CreateReadableDocument) which expose that functionality. So now you can use it like this:

```go
result, _ := trafilatura.Extract(r, opts)
readableDoc := trafilatura.CreateReadableDocument(result)

// To print the HTML output, you can use it with go-shiori/dom package
fmt.Println(dom.OuterHTML(readableDoc))
```
