### ISSUE TITLE
Extract text from already downloaded html

### ISSUE THREAD

**Issue by ZJaume** [markusmobius/go-trafilatura#5]
Can this tool be used to extract text with an html downloaded document as an input?

**Comment by markusmobius** [comment]
Yes, that's exactly how we are using it.

**Comment by ZJaume** [comment]
Sorry, it wasn't really clear to me reading the readme and I was trying piping it like this:
```
curl https://prompsit.com/ | ./go/bin/go-trafilatura
```
which is possible with trafilatura. But this works:
```
./go/bin/go-trafilatura index.html
```
Thanks!
