### ISSUE TITLE
Sync with upstream v1.8

### ISSUE THREAD

**Issue by derekperkins** [markusmobius/go-trafilatura#7]
Any plans to sync across any changes? A quick scan looks like most of the commits are code only, so it doesn't seem like too large of an overhaul to bring in logic tweaks.
https://github.com/adbar/trafilatura/compare/v1.5.0...v1.8.0

**Comment by salarali** [comment]
https://github.com/adbar/trafilatura/releases/tag/v1.10.0 is out now as well.

**Comment by markusmobius** [comment]
We are looking into updating the go code to 1.10 asap.

**Comment by derekperkins** [comment]
Thanks for your diligence working on this port!

**Comment by derekperkins** [comment]
Thanks for the 1.10 release and all the commits to make it happen @RadhiFadlillah

**Comment by RadhiFadlillah** [comment]
You are welcome! I hope it works well for you.

By the way, currently Trafilatura v1.11.0 is already released several days ago. I'm already halfway on porting it, so expect for this port to catch up in several days.
