### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by GingerMoon** [markusmobius/go-trafilatura#8]
there seems to be memory leak, do you have any idea/insight?
![image](https://github.com/markusmobius/go-trafilatura/assets/8342412/48c380b8-669f-41c3-937a-e1a61b89e386)

below is the pprof dump:
[pprof.zip](https://github.com/markusmobius/go-trafilatura/files/15059412/pprof.zip)

**Comment by RadhiFadlillah** [comment]
Hi @GingerMoon 

I've checked your pprof dump and it actually looks pretty normal. The graph on your screenshot is for `alloc_objects`, which as far as I know is not really suitable for detecting memory leaks. This is nicely explained in an awesome article by Julia Evans [here](https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/):

> go tool pprof has the option to show you either allocation counts or in use memory. If you’re concerned with the amount of memory being used, you probably want the inuse metrics, but if you’re worried about time spent in garbage collection, look at allocations!
>
> ```
> -inuse_space      Display in-use memory size
> -inuse_objects    Display in-use object counts
> -alloc_space      Display allocated memory size
> -alloc_objects    Display allocated object counts
> ```

 So, let's check out the `inuse_space`. I personally prefer flamegraph than the normal graph, so here is its screenshot:

![flamegraph of inuse_space for entire app](https://github.com/markusmobius/go-trafilatura/assets/6129042/37e4b0e9-f46b-4b69-97e9-ed6898f9f715)

From that graph, we can see your entire app uses 1.33 GB. Now, let's see how much `go-trafilatura` use in your application:

![flamegraph of inuse_space for go-trafilatura](https://github.com/markusmobius/go-trafilatura/assets/6129042/40a60303-4179-431e-a39c-5a1d5aabff3e)

As you can see, `go-trafilatura` function only use 5.58 MB or only 0.4% of your entire app. So I believe there are no memory leak occurred.

---

By the way, if you look at `alloc_space` you will se that Go allocates a whopping 0.17 TB memories for your app:

![flamegraph of alloc_space for entire app](https://github.com/markusmobius/go-trafilatura/assets/6129042/abfec0e0-3451-4c3d-b8ea-b8f72cf3cc49)

This is actually a normal behavior for Golang apps. Fro [Go's FAQ](https://go.dev/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory):

> The Go memory allocator reserves a large region of virtual memory as an arena for allocations. This virtual memory is local to the specific Go process; the reservation does not deprive other processes of memory.
