### ISSUE TITLE
No End Of Line

### ISSUE THREAD

**Issue by jhezjkp** [markusmobius/go-trafilatura#9]
<img width="568" alt="noeol" src="https://github.com/user-attachments/assets/1aeacfff-f32f-4bbf-b664-0b9288ce6c85">

<img width="308" alt="eee" src="https://github.com/user-attachments/assets/94975759-e9d1-4aa6-82c2-dde7b36a307a">

could you fix this?

thank you.

It's an awesome tool!

**Comment by RadhiFadlillah** [comment]
It should be fixed by [49d4be0](https://github.com/markusmobius/go-trafilatura/commit/49d4be03505a25a34232bde60b4aabbfb0e65ce8).
